### ISSUE TITLE
Migrate to NestJS v10

### ISSUE THREAD

**Issue by belyaev-dev** [kenso312/nestjs-v10-webpack-boilerplate#46]
### What is the motivation / use case for changing the behavior?

New NestJS version is out!

### Describe the solution you'd like

We can safely migrate using npm-check-updates and fix the errors that we find during testing

For example, [eslint-plugin-prettier issue](https://github.com/prettier/eslint-plugin-prettier/issues/562) requires to update it manually to eslint-plugin-prettier@alpha - probably needs rolling back prettier plugin to avoid it until stable version comes out

**Comment by kenso312** [comment]
Thanks for the report, [latest version](https://github.com/kenso312/nestjs-v10-webpack-boilerplate/releases/tag/v2.3.0) is released, it also integrated with SWC for better performance (it seems stable to integrate now for v10). I see your reported issue should be fixed in the [v5.0.0](https://github.com/prettier/eslint-plugin-prettier/releases/tag/v5.0.0), so I am able to upgrade all packages without any issue, but anyway thanks.
