### ISSUE TITLE
Issues with import/no-extraneous-depedencies in VSCode

### ISSUE THREAD

**Issue by belyaev-dev** [kenso312/nestjs-v10-webpack-boilerplate#50]
### Steps to reproduce

I'm having issues with this rule when using VSCode, for example
1. pnpm add supertokens-node

### Expected behavior

Package is installed and can be imported with no eslint errors

### Current behavior

'supertokens-node' should be listed in the project's dependencies. Run 'npm i -S supertokens-node' to add it eslint[import/no-extraneous-dependencies](https://github.com/import-js/eslint-plugin-import/blob/v2.28.0/docs/rules/no-extraneous-dependencies.md)

### Node.js version

18

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

### Other

The issue persists only in IDE. Running pnpm lint doesn't show any errors

Looks like that's the reason
https://github.com/import-js/eslint-plugin-import/issues/1177

**Comment by kenso312** [comment]
Are you sure the error is persistent? Because I have also faced your issue before but usually it will be disappear when I restart the VSCode. I am not quite sure the reason but the issue is not related to my boilerplate since I think the rules still have the value to keep, so I will not turn it off at this moment.
