### ISSUE TITLE
Error: Cannot find module 'src/../package.json'

### ISSUE THREAD

**Issue by eamd-wq** [kenso312/nestjs-v10-webpack-boilerplate#99]
### Steps to reproduce

1. pnpm i
2. pnpm dev

Error: Cannot find module 'src/../package.json'

May I ask if I have missed any key information?

node version: 18.18.2
pnpm version: 8.10.4

### Expected behavior

null

### Current behavior

null

### Node.js version

18.18.2

### In which operating systems have you tested?

- [ ] macOS
- [x] Windows
- [ ] Linux

**Comment by kenso312** [comment]
Thanks for the report, the issue seems to stem from the TSC path resolution problem, which specifically manifests in Windows environments. As I hadn't previously ran development mode on a Windows environment, this particular issue escaped my notice. While I didn't delve deeply into the problem, I did discover a workaround by appending "./" to the alias path records in the tsconfig.json file. The [latest version](https://github.com/kenso312/nestjs-v10-webpack-boilerplate/releases/tag/v2.5.1) is released and should be able to support Windows environment.
